### ISSUE TITLE
Add Kindle Store Option

### ISSUE THREAD

**Issue by ymnder** [operando/tonkotsu#9]
Hi @operando :-) Thank you for your great tool, tonkotsu!!
Tonkotsu does not have a option which check app on Kindle Store....
It is important to automatically check update there because its waiting time is absolutely too long.

And I made a feature of  Kindle Store Update Checker.
May I send a pull request?

**Comment by operando** [comment]
Merged https://github.com/operando/tonkotsu/pull/10
